In [36]:
import torch

In [37]:
import pandas as pd
import numpy as np

In [38]:
device="cuda" if torch.cuda.is_available() else "cpu"

In [6]:
tor=torch.tensor(8)
tor

tensor(8)

In [8]:
tor.dim()

0

In [11]:
tor.shape

torch.Size([])

In [12]:
tor.size()

torch.Size([])

In [14]:
tor.dtype

torch.int64

In [28]:
tor2=torch.tensor([1,2,3,4])
tor3=torch.tensor([1,2,3])
tor4=torch.tensor([[1,2,3],[2,3,4]])
tor5=torch.tensor([[1,2,3],[2,3,4],[5,6,7]])
tor6=torch.tensor([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
tor2,tor3,tor4,tor5,tor6

(tensor([1, 2, 3, 4]),
 tensor([1, 2, 3]),
 tensor([[1, 2, 3],
         [2, 3, 4]]),
 tensor([[1, 2, 3],
         [2, 3, 4],
         [5, 6, 7]]),
 tensor([[ 1,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9],
         [10, 11, 12]]))

In [30]:
tor2.dim(),tor3.dim(),tor4.dim(),tor5.dim(),tor6.dim()

(1, 1, 2, 2, 2)

In [29]:
tor2.shape,tor3.shape,tor4.shape,tor5.shape,tor6.shape

(torch.Size([4]),
 torch.Size([3]),
 torch.Size([2, 3]),
 torch.Size([3, 3]),
 torch.Size([4, 3]))

In [34]:
tor7=torch.tensor([[[1,2,3],[4,5,6],[7,8,9]]])
tor8=torch.tensor([[[11,22,33],[44,55,66],[77,88,99],[99,10,1]]])
tor7,tor8

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 tensor([[[11, 22, 33],
          [44, 55, 66],
          [77, 88, 99],
          [99, 10,  1]]]))

In [33]:
tor7.dim(),tor7.shape

(3, torch.Size([1, 3, 3]))

In [35]:
tor8.dim(),tor8.shape

(3, torch.Size([1, 4, 3]))

In [40]:
tor9=torch.tensor([[[1,2,3]],[[4,5,6]]])
tor9

tensor([[[1, 2, 3]],

        [[4, 5, 6]]])

In [41]:
tor9.dim(),tor9.shape

(3, torch.Size([2, 1, 3]))

Reshaping the tensor into defined shape
returns view of defined shape using same memory
stacking-combining  multiple tensors either horizantally or vertically
squeeze-removes all 1 dimension from tensor
unsqueeze-add 1 dimension to target tensor
permute-return view of input with dimensions permuted or swapped in certain way

In [44]:
x=torch.arange(1.0,10.0)
x,x.dim(),x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), 1, torch.Size([9]))

In [45]:
x=x.reshape(1,9)
x,x.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [46]:
x=x.reshape(3,3)
x,x.shape

(tensor([[1., 2., 3.],
         [4., 5., 6.],
         [7., 8., 9.]]),
 torch.Size([3, 3]))

In [47]:
x=x.reshape(9,1)
x,x.shape

(tensor([[1.],
         [2.],
         [3.],
         [4.],
         [5.],
         [6.],
         [7.],
         [8.],
         [9.]]),
 torch.Size([9, 1]))

In [48]:
z=x.view(9)

In [49]:
x[8:]=9.5

In [50]:
x

tensor([[1.0000],
        [2.0000],
        [3.0000],
        [4.0000],
        [5.0000],
        [6.0000],
        [7.0000],
        [8.0000],
        [9.5000]])

In [51]:
z

tensor([1.0000, 2.0000, 3.0000, 4.0000, 5.0000, 6.0000, 7.0000, 8.0000, 9.5000])

In [53]:
xv_stack=torch.stack([z,z,z])#default dim=0 vertial stacking
xv_stack

tensor([[1.0000, 2.0000, 3.0000, 4.0000, 5.0000, 6.0000, 7.0000, 8.0000, 9.5000],
        [1.0000, 2.0000, 3.0000, 4.0000, 5.0000, 6.0000, 7.0000, 8.0000, 9.5000],
        [1.0000, 2.0000, 3.0000, 4.0000, 5.0000, 6.0000, 7.0000, 8.0000, 9.5000]])

In [54]:
xv_stack2=torch.stack([z,z,z],dim=0)
xv_stack2

tensor([[1.0000, 2.0000, 3.0000, 4.0000, 5.0000, 6.0000, 7.0000, 8.0000, 9.5000],
        [1.0000, 2.0000, 3.0000, 4.0000, 5.0000, 6.0000, 7.0000, 8.0000, 9.5000],
        [1.0000, 2.0000, 3.0000, 4.0000, 5.0000, 6.0000, 7.0000, 8.0000, 9.5000]])

In [55]:
xh_stack3=torch.stack([z,z,z],dim=1)
xh_stack3 #horizantal stacking dim=1


tensor([[1.0000, 1.0000, 1.0000],
        [2.0000, 2.0000, 2.0000],
        [3.0000, 3.0000, 3.0000],
        [4.0000, 4.0000, 4.0000],
        [5.0000, 5.0000, 5.0000],
        [6.0000, 6.0000, 6.0000],
        [7.0000, 7.0000, 7.0000],
        [8.0000, 8.0000, 8.0000],
        [9.5000, 9.5000, 9.5000]])

In [56]:
#squeeze removing one dimensions
x.shape

torch.Size([9, 1])

In [59]:
x=torch.squeeze(x)

In [60]:
x.shape

torch.Size([9])

In [65]:
a=torch.tensor([1,2,3])
print(a.shape)
a=torch.squeeze(a)
print(a.shape)

torch.Size([3])
torch.Size([3])


In [66]:
x_unsqueezed_1=torch.unsqueeze(x,dim=0)
x_unsqueezed_1.shape

torch.Size([1, 9])

In [67]:
x_unsqueezed_2=torch.unsqueeze(x,dim=1)
x_unsqueezed_2.shape

torch.Size([9, 1])

In [69]:
x_unsqueezed_2=torch.permute(x_unsqueezed_2,dims=(1,0))

In [70]:
x_unsqueezed_2.shape

torch.Size([1, 9])